pipeline {
    agent any
    tools {
        maven 'mavenlocal'  // Name configured in Jenkins Global Tool Configuration
        jdk 'jdklocal'     // Name configured in Jenkins Global Tool Configuration
    }
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/JasonkDaniel/jenkinspringboot.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Package') {
            steps {
                sh 'mvn package'
            }
        }
    }
}